#!/bin/bash
# Script to prepare test database for OnionRM tests

set -e

DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-7101}"
DB_USER="${DB_USER:-postgres}"
DB_NAME="onionrm_test"
TEST_USER="onionrm_test"
TEST_PASSWORD="test123"

echo "🔧 Preparing test database..."
echo "   Host: $DB_HOST:$DB_PORT"
echo "   User: $DB_USER"
echo ""

# Wait for PostgreSQL to be ready
echo "⏳ Waiting for PostgreSQL to be ready..."
for i in {1..30}; do
  if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -c '\q' 2>/dev/null; then
    echo "✓ PostgreSQL is ready"
    break
  fi
  if [ $i -eq 30 ]; then
    echo "❌ PostgreSQL is not responding after 30 attempts"
    exit 1
  fi
  sleep 1
done

# Drop existing database if it exists
echo ""
echo "🗑️  Dropping existing database (if exists)..."
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -c "DROP DATABASE IF EXISTS $DB_NAME;" 2>/dev/null || true

# Create database
echo "📦 Creating database '$DB_NAME'..."
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -c "CREATE DATABASE $DB_NAME;"

# Drop existing user if exists
echo "👤 Creating test user '$TEST_USER'..."
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d postgres -c "DROP USER IF EXISTS $TEST_USER;" 2>/dev/null || true

# Create user with password
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d postgres -c "CREATE USER $TEST_USER WITH PASSWORD '$TEST_PASSWORD';"

# Grant privileges
echo "🔐 Granting privileges..."
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $TEST_USER;"
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "GRANT ALL ON SCHEMA public TO $TEST_USER;"

# Create test/config.js
echo ""
echo "📝 Creating test/config.js..."
cat > test/config.js << EOF
// Test configuration for OnionRM
// Auto-generated by scripts/prepare-test-db.sh

exports.postgres = {
	host     : "$DB_HOST:$DB_PORT",
	user     : "$TEST_USER",
	password : "$TEST_PASSWORD",
	database : "$DB_NAME"
};
EOF

echo "✓ test/config.js created"

# Verify connection
echo ""
echo "🔍 Verifying test user can connect..."
if PGPASSWORD="$TEST_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$TEST_USER" -d "$DB_NAME" -c "SELECT version();" > /dev/null 2>&1; then
	echo "✓ Test user connection successful"
else
	echo "❌ Test user connection failed"
	exit 1
fi

echo ""
echo "✅ Database preparation complete!"
echo ""
echo "You can now run tests with:"
echo "  make test"
echo "  or"
echo "  ORM_PROTOCOL=postgres node test/run"
